// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using ConsoleApplication1;
using ConsoleApplication1.Models;
using Microsoft.Rest;

namespace ConsoleApplication1
{
    public static partial class ValuesExtensions
    {
        /// <param name='operations'>
        /// Reference to the ConsoleApplication1.IValues.
        /// </param>
        public static IList<string> Get(this IValues operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IValues)s).GetAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the ConsoleApplication1.IValues.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<string>> GetAsync(this IValues operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<string>> result = await operations.GetWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the ConsoleApplication1.IValues.
        /// </param>
        /// <param name='dateTimeOffset'>
        /// Required.
        /// </param>
        public static string PostRawDate(this IValues operations, DateTimeOffset dateTimeOffset)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IValues)s).PostRawDateAsync(dateTimeOffset);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the ConsoleApplication1.IValues.
        /// </param>
        /// <param name='dateTimeOffset'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<string> PostRawDateAsync(this IValues operations, DateTimeOffset dateTimeOffset, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<string> result = await operations.PostRawDateWithOperationResponseAsync(dateTimeOffset, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the ConsoleApplication1.IValues.
        /// </param>
        /// <param name='wrapper'>
        /// Required.
        /// </param>
        public static string PostWrappedRawDate(this IValues operations, OffsetWrapper wrapper)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IValues)s).PostWrappedRawDateAsync(wrapper);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the ConsoleApplication1.IValues.
        /// </param>
        /// <param name='wrapper'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<string> PostWrappedRawDateAsync(this IValues operations, OffsetWrapper wrapper, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<string> result = await operations.PostWrappedRawDateWithOperationResponseAsync(wrapper, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
